name: 'Sync GitHub Repo Data'
description: 'An action that syncs GitHub repository data to database'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'

inputs:
  database-url:
    description: 'Database URL'
    required: true
  access-token:
    description: 'GitHub access token'
    required: true
  repo-full-name:
    description: 'GitHub repository full name'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile' 

  # Pass the inputs and secret values as environment variables to the Docker container
  env:
    DATABASE_URL: ${{ inputs.database-url }}
    ACCESS_TOKEN: ${{ inputs.access-token }}
    PYPI_PACKAGE: ${{ inputs.pypi-package }}
    REPO_FULL_NAME: ${{ inputs.repo-full-name }}